name: 'Demonstrate Dependency Caching'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository's code
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Cache the node_modules directory
      - name: 'Cache node modules'
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-3a85937

      # Step 4: Echo the cache hit/miss result
      - name: 'prime-cache-3a85937'
        run: echo "Cache hit was: ${{ steps.cache-npm.outputs.cache-hit }}"

      # Step 5: Install dependencies (will be fast if cache was hit)
      - name: 'Install dependencies'
        run: npm install

      # Step 6: Run a test to confirm installation
      - name: 'Run test script'
        run: npm test

