name: 'Demonstrate Dependency Caching'

on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # 2. Sets up Node.js for the runner
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Caches the node_modules directory to speed up subsequent runs
      - name: 'Cache node modules'
        id: cache-npm # We give this step an ID to reference its output
        uses: actions/cache@v4
        with:
          # The path to the folder we want to cache
          path: node_modules
          # The unique key for the cache. The first run will create the cache with this key.
          key: cache-3a85937

      # 4. A step specifically named to meet the requirements
      - name: 'prime-cache-3a85937'
        run: echo "Cache hit result was: ${{ steps.cache-npm.outputs.cache-hit }}"

      # 5. Installs dependencies. This will be very fast if the cache was restored.
      - name: 'Install dependencies'
        run: npm install

      # 6. Runs a simple test from package.json to verify dependencies are working
      - name: 'Run test script'
        run: npm test

