name: 'Demonstrate Dependency Caching'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Cache node modules'
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-3a85937

      - name: 'prime-cache-3a85937'
        run: |
          echo "Cache hit was: ${{ steps.cache-npm.outputs.cache-hit }}"


      - name: 'Install dependencies'
        run: npm install

      - name: 'Run test script'
        run: npm test
